export const profile = {
  name: 'Mohammed Shakib',
  role: 'B.Tech CSE (AI & ML) Student',
  github: 'https://github.com/MohammedShakib-645',
  linkedin: 'https://www.linkedin.com/in/mohammed-shakib-56b28437a/',
  email: '5645mohammedshakib@gmail.com',
  phone: '9381938684',
  whatsapp: 'https://wa.me/919381938684',
  location: 'Hyderabad, Telangana, India',
}

export const navigation = [
  { label: 'About', href: '#about' },
  { label: 'Journey', href: '#journey' },
  { label: 'Skills', href: '#skills' },
  { label: 'Certifications', href: '#certifications' },
  { label: 'Work', href: '#work' },
  { label: 'Exploring', href: '#exploring' },
  { label: 'GitHub', href: '#github' },
  { label: 'Achievements', href: '#achievements' },
  { label: 'Contact', href: '#contact' },
]

export const projects = [
  {
    number: '01',
    title: 'Student Record Management System',
    shortTitle: 'Structured by design.',
    category: 'PROGRAMMING FUNDAMENTALS',
    technologies: ['C'],
    description: 'A console-based student record management project focused on structured data handling and CRUD-style operations.',
    href: 'https://github.com/MohammedShakib-645/student-record-system',
    linkLabel: 'VIEW WEB VERSION',
    note: 'The linked repository contains the web version of this project.',
    visual: 'records',
  },
  {
    number: '02',
    title: 'Simple Calculator',
    shortTitle: 'Small program. Solid foundations.',
    category: 'LOGIC & PROBLEM SOLVING',
    technologies: ['Python'],
    description: 'A simple calculator project built while learning Python programming fundamentals.',
    href: 'https://github.com/MohammedShakib-645/calculator',
    linkLabel: 'VIEW WEB VERSION',
    note: 'The linked repository contains the HTML, CSS and JavaScript version.',
    visual: 'calculator',
  },
  {
    number: '03',
    title: 'Exam Strategy Simulator',
    shortTitle: 'A more considered approach.',
    category: 'PRACTICAL PROBLEM SOLVING',
    technologies: ['Python'],
    description: 'A Python project exploring exam preparation and study planning.',
    href: 'https://github.com/MohammedShakib-645/exam-strategy-simulator',
    linkLabel: 'VIEW REPOSITORY',
    note: '',
    visual: 'exam',
  },
  {
    number: '04',
    title: 'TypeMaster',
    shortTitle: 'Find your flow.',
    category: 'WEB DEVELOPMENT',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    description: 'A web project exploring typing interactions with HTML, CSS and JavaScript.',
    href: 'https://github.com/MohammedShakib-645/TypeMaster',
    linkLabel: 'VIEW REPOSITORY',
    note: '',
    visual: 'typing',
  },
  {
    number: '05',
    title: 'GestureVision_X',
    shortTitle: 'Beyond the keyboard.',
    category: 'COMPUTER VISION EXPLORATION',
    technologies: ['Python', 'Computer Vision'],
    description: 'Exploring real-time hand gesture recognition through Python and computer vision.',
    href: 'https://github.com/MohammedShakib-645/GestureVision_X',
    linkLabel: 'VIEW REPOSITORY',
    note: '',
    visual: 'gesture',
  },
] as const

export const skillGroups = [
  { name: 'Programming', index: '01', items: ['C', 'Python', 'Java'] },
  { name: 'Web', index: '02', items: ['HTML', 'CSS', 'JavaScript'] },
  { name: 'Computer science', index: '03', items: ['DSA', 'Algorithms', 'OOP', 'Problem Solving', 'SQL / Database Fundamentals'] },
  { name: 'Tools', index: '04', items: ['Git', 'GitHub', 'VS Code'] },
  { name: 'Currently learning', index: '05', items: ['Java', 'Python', 'DSA', 'Web Development', 'AI / ML'] },
]

export const certifications = [
  {
    name: 'Python for Data Science',
    issuer: 'NPTEL · IIT MADRAS',
    courseCode: 'NOC26-CS80',
    score: 'SCORE 69%',
    grade: 'ELITE',
    period: 'JAN–FEB 2026',
    duration: '4-WEEK COURSE',
    href: 'https://archive.nptel.ac.in/noc/Ecertificate/?q=NPTEL26CS80S457303340',
  },
]
